### ISSUE TITLE
Collaboration to make the best Spotify CLI

### ISSUE THREAD

**Issue by owenthereal** [joshuathompson/baton#10]
Hello @joshuathompson,

I made https://github.com/jingweno/spotctl before I discovered your project. Looks like we have quite a bit of overlap. Would you be interested in joining force? Feel free to ping me.

🍻

**Comment by joshuathompson** [comment]
Hey @jingweno, what did you have in mind?  Are you envisioning a more complete version of your real-time player idea?  It seems like there are two kinds of users, those who like to run a command and keep the Spotify view open and those who want to run a command and continue using their terminal for other tasks.

I'm open to the idea of joining force.

**Comment by joshuathompson** [comment]
Think I'm just going to maintain it separately, this one is mostly in a 'complete' state as far as what I personally set out to accomplish.
