### ISSUE TITLE
Transfer to device does not happen

### ISSUE THREAD

**Issue by dangerfish96** [joshuathompson/baton#13]
I have set up a raspberry pi with raspotify and it is recognized by `baton devices`.
But `baton transfer <id>` does not do anything.

**Comment by joshuathompson** [comment]
Hey @dangerfish96, thanks for the ticket.  Do you get an error saying that there was a failure to transfer playback or does it act like it happened successfully?

I'm able to switch between my phone and PC.  Can you try another device if you're able?

**Comment by dangerfish96** [comment]
It says the transfer is successfull.
And it‘s only with this device/ raspotify. If music is already playing with raspotify it is transferable to another device. It is also possible to transfer it to raspotify from spotify itself

**Comment by christopher-dG** [comment]
This is happening to me too when transferring from my phone to [spotifyd](https://github.com/Spotifyd/spotifyd). However the other way around from spotifyd to phone works.

Also transfered should be spelled transferred :sweat_smile:

**Comment by dangerfish96** [comment]
Here is the output of strace:
https://pastebin.com/E5FN9NTd

**Comment by dangerfish96** [comment]
The Spotify has an api endpoint for transfering devices.
It uses device_ids instead of device_id which is used in baton.
Thats why it does not work.

**Comment by dangerfish96** [comment]
I made a small workaround that fixes the transfer issue. But I don't know how to code in golang, so...

https://pastebin.com/SzfxM1u9

**Comment by joshuathompson** [comment]
@dangerfish96 I just tried my hand at fixing it using the information you gave me. Grab the new version and let me know if that works for you.

Also fixed the typo @christopher-dG brought up 😅

**Comment by christopher-dG** [comment]
It's working on my end! This is really huge for me, I can finally drop the desktop app. Thank you so much!

**Comment by joshuathompson** [comment]
Awesome! Happy to close this for now. Feel free to reopen.
