### ISSUE TITLE
search error "invalid argument"

### ISSUE THREAD

**Issue by jojh40** [joshuathompson/baton#14]
Hi!
Very nice work but I have a problem using search function.

Every search gets error invalid argument.

For example:
./baton search artist Iron Maiden
2018/02/23 20:56:43 invalid argument
Other functions like next, repeat, status and devices are working.

**Comment by ghyde** [comment]
What version of `baton` are you running, and what OS are you using?

**Comment by joshuathompson** [comment]
Yeah if it's an old version then you would have to change your command to `baton search artist "Iron Maiden"`.  Would be interesting if that isn't the problem.

**Comment by jojh40** [comment]
Latest version 0.1.3
Tried ./baton search artist "iron Maiden" - same error
2018/02/24 15:45:33 invalid argument

Im using Ubuntu

**Comment by joshuathompson** [comment]
Year later, still can't reproduce this issue. Feel free to reopen with more info if it somehow still persists.
