### ISSUE TITLE
Share shows API URL

### ISSUE THREAD

**Issue by cassiobock** [joshuathompson/baton#15]
Using `baton share` outputs the URI and the API urls, where it should replace or include some "shareable" URL.

Current output:
```
baton share  
URI: spotify:track:2OBgZrayUVupeEtt1eu2V4
URL: https://api.spotify.com/v1/tracks/2OBgZrayUVupeEtt1eu2V4
```

It should include some URL that I could send to someone, e.g.: https://open.spotify.com/track/2OBgZrayUVupeEtt1eu2V4

**Comment by joshuathompson** [comment]
This was added in your PR #18. Thanks for the contribution!
