### ISSUE TITLE
"404 not Found" search error

### ISSUE THREAD

**Issue by christopher-dG** [joshuathompson/baton#16]
Any search command shows the results just fine, but when I choose one, nothing is played and I get a log message: "404 Not Found".

```sh
[ ~ ] baton search artist foo  # Press enter to choose an artist from the TUI 
2018/06/24 12:27:28 404 Not Found
```

**Comment by joshuathompson** [comment]
Looks like a bad error, what's actually happening is it's not finding an 'active' playing device. I think if there used to not be an 'active' device then the API would auto select one. Now it appears you have to explicitly select one via a call like `baton search artist foo -d {my_device_id}` (note that all calls after this appear to work without the -d flag as the device would now be active).

Either need to get Spotify to change that functionality back, select the first device returned by `baton devices`, or allow people to select a default device.

**Comment by joshuathompson** [comment]
Went ahead and filed a ticket here https://github.com/spotify/web-api/issues/924

**Comment by christopher-dG** [comment]
Thanks for looking into this! Unfortunately this compounds with #13 to make me have to start playback on my phone (the `-d` flag doesn't do anything for my spotifyd device).

**Comment by joshuathompson** [comment]
Looks like they accept it as a bug @christopher-dG so hopefully this gets resolved for you! I have a feeling that other issue is simply an issue with the API as well.

**Comment by christopher-dG** [comment]
This is working for me now, presumably something changed upstream. I'll keep an eye out though.
