### ISSUE TITLE
add ability to like a  song

### ISSUE THREAD

**Issue by MarinPostma** [joshuathompson/baton#24]
Hi!
first of all thank you for this amazing tool :)

It would be nice if it were possible to like the currently playing song, as there is an endpoint for it : https://developer.spotify.com/documentation/web-api/reference/library/save-tracks-user/

keep up with the good work!

**Comment by joshuathompson** [comment]
@kovetskiy completed this in the above PR and I have released a `0.1.7` version, thanks!
