### ISSUE TITLE
Incorrect "Now playing" output from search

### ISSUE THREAD

**Issue by christopher-dG** [joshuathompson/baton#4]
```
$ ./baton status
Track: Sé Lest
Artist: Sigur Rós
Album: Takk
Time Elapsed: 0:09 - 8:40

$ ./baton search artist balance
# Choose the first option "Balance And Composure"
Now playing 'Sé Lest' by Sigur Rós from the album Takk

$ ./baton status
Track: Tiny Raindrop
Artist: Balance And Composure
Album: The Things We Think We're Missing
Time Elapsed: 0:04 - 3:33
```

**Comment by christopher-dG** [comment]
Looks like you've probably already encountered this yourself with your comment in `printNowPlaying`.
I addded another 300 ms to the sleep and it's working consistently for me, without feeling sluggish. I think the optimal value will depend on the user's connection.

**Comment by joshuathompson** [comment]
Your instincts are right, I did run into this haha.  You have forced my hand to fix it now.  As such, it now keeps track of the selected item and reports it properly when exiting gocui.
