### ISSUE TITLE
Only allowing one-word search arguments doesn't make sense

### ISSUE THREAD

**Issue by christopher-dG** [joshuathompson/baton#5]
```
$ ./baton search track foo bar
Error: accepts 1 arg(s), received 2
Usage:
  baton search track "track name" [flags]

Flags:
  -h, --help   help for track
```
I'm not sure what `cobra.ExactArgs(1)` does exactly, but correct behaviour is definitely just combining all the words into a single argument string to the search function.

edit: of course there's the option of quoting the string, but that's not too user friendly imo.

**Comment by joshuathompson** [comment]
Agreed, it's not user-friendly.  Allowing multi-word arguments in Play and Search now.
