### ISSUE TITLE
Add and remove songs from Playlists

### ISSUE THREAD

**Issue by joshuathompson** [joshuathompson/baton#9]
Reddit user /u/StormsMessenger would like the ability to add/remove songs to playlists

**Comment by joshuathompson** [comment]
Don't think there's a graceful way to accomplish this in the command line.  The only thing that would work seamlessly is adding to a library.  When it comes to playlists I would have to use ids.

**Comment by rafi** [comment]
@joshuathompson could you reconsider this? It would be awesome to hit <kbd>a</kbd> or <kbd>c</kbd> to copy song id, and immediately jump into list of playlists, then once I find the one I'm looking for, hitting <kbd>p</kbd> would paste the song into the playlist I'm currently viewing.

I think it's a priceless feature for someone who manages a lot of playlists.
